on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build_and_deploy:
    name: Build & Deploy
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.10"]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install the dependencies
        run: |
          python3.10 -m venv .venv && source .venv/bin/activate
          echo "Upgrading pip..."
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: Build & Deploy to gh-pages
        run: |
          source .venv/bin/activate
          pelican-themes --install theme/elegant/
          make github
