name: CI

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

  # Everyday at 1.00 UTC.
  schedule:
    - cron: "0 1 * * *"


# Cancel any running workflow if the CI gets triggered again.
concurrency:
      group: ${{ github.head_ref || github.run_id }}
      cancel-in-progress: true


jobs:
  build:
    runs-on: ubuntu-latest

    include:
    - os: ubuntu-latest
      path: ~/.cache/pip # Cache location on Ubuntu

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: "3.11.0-beta.3"

      - uses: actions/cache@v3
        with:
          path: ${{ matrix.path }}
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}-${{ hashFiles('**/requirements-dev.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install the dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt -r requirements-dev.txt

      - name: Check linter
        run: |
          echo "Checking linter conformity..."
          make lint-check

      - name: Build the site
        run: |
          pelican-themes --install theme/elegant/
          ghp-import -m "Generate Pelican site" -b gh-pages ./output -f

      - name: Publish the site
        if: ${{ github.event_name != 'pull_request' }}
        run: |
          make github
