name: CI

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

  # Everyday at 1.00 UTC.
  schedule:
    - cron: "0 1 * * *"


# Cancel any running workflow if the CI gets triggered again.
concurrency:
      group: ${{ github.head_ref || github.run_id }}
      cancel-in-progress: true


jobs:
  run-tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.10"]
        include:
        - os: ubuntu-latest
          path: ~/.cache/pip # Cache location on Ubuntu
        - os: macos-latest
          path: ~/Library/Caches/pip # Cache location on MacOS

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - uses: actions/cache@v2
        with:
          path: ${{ matrix.path }}
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}-${{ hashFiles('**/requirements-dev.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install the Dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt -r requirements-dev.txt

      - name: Check Linter
        run: |
          echo "Checking linter conformity..."
          make lint-check

      - name: Build and deploy to gh-pages
        run: |
          source .venv/bin/activate
          pelican-themes --install theme/elegant/
          make github
