on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test: # Run test on the index generation script.
    name: Test create_index.py script
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-11]
        python-version: ["3.10"]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install the test dependencies
        run: |
          echo "Upgrading pip ...."
          python -m pip install --upgrade pip
          python -m pip install -r requirements-dev.txt

      - name: Check linter
        run: |
          echo "Checking black formatting..."
          python3 -m black --check .
          echo "Checking isort formatting..."
          python3 -m isort --check .
          echo "Checking flake8 formatting..."
          python3 -m flake8 .

      - name: Run the tests
        run: |
          pytest -s -v
